package lanyou.rzzl.drools.drivelicenseapplicant;

import lanyou.rzzl.drools.drivelicenseapplicant.UserInfo;

rule "you can apply drivinglicense if your age is older than 18"
    no-loop true
    when 
        $u:UserInfo(user_id!=null)
    then
        //UserInfo ui = new UserInfo(1,"wumin",29);
        //insert(ui);
        $u.setUser_name("wuminhaha");
        $u.setUser_age(29);
        insert($u);
end