package lanyou.rzzl.drools.drivelicenseapplicant;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public UserInfo() {
    }




}