package lanyou.rzzl.loancheck.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("审核要点")
@org.kie.api.definition.type.Description("描述审核要点")
public class checkPoint implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("sex")
	private java.lang.Integer sex;

	@org.kie.api.definition.type.Label(value = "\u5E74\u9F84")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label(value = "\u5E74\u6536\u5165")
	private java.lang.Double income;

	public checkPoint() {
	}

	public java.lang.Integer getSex() {
		return this.sex;
	}

	public void setSex(java.lang.Integer sex) {
		this.sex = sex;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Double getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Double income) {
		this.income = income;
	}

	public checkPoint(java.lang.Integer sex, java.lang.Integer age,
			java.lang.Double income) {
		this.sex = sex;
		this.age = age;
		this.income = income;
	}

}