package lanyou.rzzl.loancheck.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckPoint implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CheckPoint() {
    }




}